import random

provincias_y_capitales = [
    ['Buenos Aires', 'La Plata'],
    ['Catamarca', 'San Fernando del Valle de Catamarca'],
    ['Chaco', 'Resistencia'],
    ['Chubut', 'Rawson'],
    ['Córdoba', 'Córdoba'],
    ['Corrientes', 'Corrientes'],
    ['Entre Ríos', 'Paraná'],
    ['Formosa', 'Formosa'],
    ['Jujuy', 'San Salvador de Jujuy'],
    ['La Pampa', 'Santa Rosa'],
    ['La Rioja', 'La Rioja'],
    ['Mendoza', 'Mendoza'],
    ['Misiones', 'Posadas'],
    ['Neuquén', 'Neuquén'],
    ['Río Negro', 'Viedma'],
    ['Salta', 'Salta'],
    ['San Juan', 'San Juan'],
    ['San Luis', 'San Luis'],
    ['Santa Cruz', 'Río Gallegos'],
    ['Santa Fe', 'Santa Fe'],
    ['Santiago del Estero', 'Santiago del Estero'],
    ['Tierra del Fuego', 'Ushuaia'],
    ['Tucumán', 'San Miguel de Tucumán'],
]
